services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    container_name: PEOPLE_DB
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password10*"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - helppeople_network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  backend:
    build: ./people_back
    container_name: backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./people_back:/app
      - /app/node_modules
    networks:
      - helppeople_network
    command: npm run start:dev

  frontend:
    build: ./people_front
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:3000"
    volumes:
      - ./people_front:/app
      - /app/node_modules
      - /app/.next
    networks:
      - helppeople_network
    command: npm run dev

volumes:
  sqlserver_data:

networks:
  helppeople_network: