name: helppeople_stack
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    container_name: helppeople_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password10*"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - helppeople_network

  backend:
    build: 
      context: ./people_back
      dockerfile: Dockerfile
    container_name: helppeople_backend
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./people_back:/app
      - /app/node_modules
    networks:
      - helppeople_network

  frontend:
    build: 
      context: ./people_front
      dockerfile: Dockerfile
    container_name: helppeople_frontend
    restart: always
    depends_on:
      - database
    ports:
      - "3002:3000"
    networks:
      - helppeople_network

volumes:
  sqlserver_data:

networks:
  helppeople_network: